services:
  api.url-shortener:
    image: url-shortener:latest
    build: ./
    env_file: ./.env
    container_name: api.url-shortener
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_POSTGRES_HOST}
      - DB_PORT=${DB_POSTGRES_PORT}
      - DB_USER=${DB_POSTGRES_USER}
      - DB_PASSWORD=${DB_POSTGRES_PASSWORD}
      - DB_NAME=${DB_POSTGRES_NAME}
    volumes:
      - ./:/app
    command: sh -c "yarn --ignore-scripts && yarn run start:dev"
    depends_on:
      - db.postgres.url-shortener

  db.postgres.url-shortener:
    image: postgres:latest
    container_name: db.postgres.url-shortener
    restart: always
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - '${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: